global:
  # TODO: try using makefile and envsubst
  # alertmanager program can read only input only from .yml file.
  # It does not support for getting environment variable 
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: '$SMTPFROM'
  smtp_auth_username: '$SMTPAUTHUSERNAME'
  smtp_auth_password: '$SMTPAUTHPASSWORD'

# templates:
#   - '/etc/alertmanager/template/*.tmpl'

route:
  receiver: admin

receivers:
  - name: admin
    email_configs:
      - to: '$TO'