groups:
  - name: prometheus-rules
    rules:
      - alert: NodeExporterDown
        expr: up{job='node_exporter'}==0
        for: 1m
        labels:
           severity: warning
        annotations:
          description: '{{ $labels.instance }} of job {{ $labels.job }} has
                        been down for more than 1 minute'
          summary: 'Node Exporter is down more than 1 min'