{
 "title": "Target Monitor Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  { "title": "Health", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Targets Health",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up", "legendFormat": "{{ job }}" }
   ]
  },
  { "title": "Application Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Python Exporter - My Computer Usage",
   "type": "stat",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "computer_usage", "legendFormat": "{{ resource_label }}" }
   ]
  },
  {
   "title": "Go Exporter - Request Count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "count_total" }
   ]
  }
 ]
}